name: deepstar
channels:
  - defaults
dependencies:
  - appdirs=1.4.3=py35h28b3542_0
  - appnope=0.1.0=py35hd172556_0
  - asn1crypto=0.24.0=py35_0
  - attrs=18.2.0=py35h28b3542_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - bleach=2.1.4=py35_0
  - ca-certificates=2019.1.23=0
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35h6174b99_1
  - constantly=15.1.0=py35h28b3542_0
  - cryptography=2.3.1=py35hdbc3d79_0
  - dbus=1.13.6=h90a0687_0
  - decorator=4.3.0=py35_0
  - entrypoints=0.2.3=py35_2
  - expat=2.2.6=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - html5lib=1.0.1=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h4b95b61_1
  - idna=2.7=py35_0
  - incremental=17.5.0=py35_0
  - ipykernel=4.10.0=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hf129286_0
  - ipywidgets=7.4.1=py35_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py35h2dd9e4b_0
  - jupyter=1.0.0=py35_7
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35hd2aa692_1
  - jupyter_core=4.4.0=py35_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.36=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.0=py35h1de35cc_1
  - mistune=0.8.3=py35h1de35cc_1
  - nbconvert=5.3.1=py35_0
  - nbformat=4.4.0=py35h41c2038_0
  - ncurses=6.1=h0a44026_1
  - notebook=5.6.0=py35_0
  - openssl=1.0.2r=h1de35cc_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py35_1
  - parso=0.3.1=py35_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35h9517181_0
  - prometheus_client=0.3.1=py35h28b3542_0
  - prompt_toolkit=1.0.15=py35h93950c5_0
  - ptyprocess=0.6.0=py35_0
  - pyasn1=0.4.5=py_0
  - pyasn1-modules=0.2.2=py35_0
  - pycparser=2.19=py35_0
  - pygments=2.2.0=py35h392a662_0
  - pyopenssl=18.0.0=py35_0
  - pyqt=5.9.2=py35h655552a_2
  - python=3.5.6=hc167b69_0
  - python-dateutil=2.7.3=py35_0
  - pyzmq=17.1.2=py35h1de35cc_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.4.1=py35_0
  - readline=7.0=h1de35cc_5
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35h28b3542_0
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35h0a44026_0
  - six=1.11.0=py35_1
  - sqlite=3.26.0=ha441bb4_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35hf8009f4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py35h1de35cc_0
  - traitlets=4.3.2=py35hd3d1486_0
  - twisted=18.7.0=py35h1de35cc_1
  - wcwidth=0.1.7=py35hdd0c235_0
  - webencodings=0.5.1=py35_1
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.4.1=py35_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=h1de35cc_3
  - zope=1.0=py35_1
  - zope.interface=4.5.0=py35h1de35cc_0
  - pip:
    - absl-py==0.7.0
    - chardet==3.0.4
    - enum34==1.1.6
    - future==0.17.1
    - mock==2.0.0
    - mpyq==0.2.5
    - numpy==1.16.2
    - pbr==5.1.3
    - pip==19.0.3
    - portpicker==1.3.0
    - protobuf==3.7.0
    - pygame==1.9.2
    - pysc2==2.0.2
    - requests==2.21.0
    - s2clientprotocol==4.8.3.72282.0
    - scipy==1.2.1
    - sk-video==1.1.10
    - smac==0.1.0b1
    - urllib3==1.24.1
    - websocket-client==0.55.0
    - whichcraft==0.5.2
